### ISSUE TITLE
More documentation

### ISSUE THREAD

**Issue by Spindel** [smomni/craniodistractor#1]
Hi!
You recently contacted me on Reddit for part project management tutoring, so let's get the ball rolling (Filing issue #1)

Start by adding a README that documents:

- What this is  
- Why this exists  
- How to use it   
- ( how to deploy it ) 
- How you want development to work

In the commit message, mention:
`Issue #1`   or `Closes #1`

**Comment by smomni** [comment]
Hi Spindel,

the README is currently only on the develop branch. I haven't merged master and develop branches yet but I'm doing that for release 0.1.0 (first demo prototype).
