### ISSUE TITLE
Document workflow

### ISSUE THREAD

**Issue by Spindel** [smomni/craniodistractor#2]
I'd suggest a rather simple, but structured workflow:

- File issues for those features you're looking to get. They can be small or big, as long as they are solveable. 
   you should be able to tell when something is done from reading the issue. Too open ended and it cannot be closed.

- Develop those issues
- Commits should touch one thing, preferrably, with a label that matches the code. IE, a change that reads "reformat foo" shouldn't add new features, etc.
- Open an Pull request /MR for your own review from the branch to master
- Try to keep the commits on an MR branch below a dozen.
- Keep the MR open for 24 hours, give people the _chance_ to comment and look at it.
- Review that the changes in there look decent

It's a perfectly valid workflow to sit down and hack, realize you just built a feature, then file an issue for this feature. It's even commendable. 

The goal is to get the _habit_ in of referring to your issues, and opening code review points _before_ merging directly to master.

"But I'm the only developer here?!"  you may think, and yes. That's why it's good to practice now.

- [x] Document your desired work flow, and open an MR for that documentation for a quick review.

**Comment by smomni** [comment]
Opened pull request #4
